# Generated by Django 5.0.2 on 2024-02-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('video_url', models.URLField()),
            ],
        ),
    ]
